# Generated by Django 6.0 on 2026-01-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
