# Generated by Django 6.0 on 2026-01-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_delete_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resno', models.AutoField(primary_key=True, serialize=False)),
                ('locno', models.IntegerField(default=0)),
                ('res_name', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(null=True)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=13, null=True)),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mem_id', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
