# Generated by Django 6.0 on 2026-01-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_foodmenu_restaurantopertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantopertime',
            name='resno',
        ),
        migrations.DeleteModel(
            name='FoodMenu',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantOperTime',
        ),
    ]
