# Generated by Django 6.0 on 2026-01-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0008_remove_restaurantopertime_resno_delete_foodmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resno', models.AutoField(primary_key=True, serialize=False)),
                ('locno', models.IntegerField(default=0)),
                ('res_name', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(null=True)),
                ('addr', models.CharField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=13, null=True)),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mem_id', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('fnm', models.CharField(max_length=100, null=True)),
                ('resno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOperTime',
            fields=[
                ('opno', models.AutoField(primary_key=True, serialize=False)),
                ('week', models.CharField(max_length=50, null=True)),
                ('open_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('resno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restaurant')),
            ],
        ),
    ]
